### ISSUE TITLE
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by Myerden** [gfx/TinyPdfReader#3]
After I downloaded the source, I can't compile the project.
When I try to compile the project Android Studio shows me error message;

> Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> com.android.build.gradle.api.BaseVariant.getJavaCompiler()Lorg/gradle/api/tasks/compile/AbstractCompile;

**My environments ;**
Android Studio 2.2.2
Java 1.8.0_25
Windows 7

**Comment by gfx** [comment]
Maybe fixed by #4.

BTW this project is just a sample code and I won't maintain it anymore.
